### ISSUE TITLE
UserStory: Task List View

### ISSUE THREAD

**Issue by hiimchrislim** [GDSCUTM-CommunityProjects/UTimeManager#11]
As a user, I want to view all of my tasks so that I can see which ones need to be completed

**Acceptance Criteria**
- [x] A header showing the date for which all the tasks are to be done for the day
- [x] Listing out all the tasks for a particular day
- [x] If a task is clicked, a box should appear showing more details about the task (Not on a separate page)
- [x] All dates, times and other information should be displayed (Only critical information)
- [x] If there are most tasks than the screen size, the task list should be scrollable
- [x] Tasks should be able to be started and ended (If ended, then it should be visibly crossed out)

**Sub Tasks**
- [x] Creating the task component (Showing critical info about task)
- [x] Creating the task list view (Contains all tasks) (See acceptance criteria for more info)

**Additional Comments**
See the design for more info
https://www.figma.com/file/sweIMEBZehqtiEKzOhx5wZ/UTimeManager-GDSC-CP-Winter-2022?node-id=0%3A1
